name: Flutter Windows, Linux, macOS, and Android Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Enable Windows Desktop Support
        run: flutter config --enable-windows-desktop

      - name: Add Windows Platform Support
        run: flutter create --platforms=windows .

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload Windows Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release/

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Install dependencies for Linux build
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Enable Linux Desktop Support
        run: flutter config --enable-linux-desktop

      - name: Add Linux Platform Support
        run: flutter create --platforms=linux .

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Linux Release
        run: flutter build linux --release

      - name: Upload Linux Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: build/linux/x64/release/bundle/

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Enable macOS Desktop Support
        run: flutter config --enable-macos-desktop

      - name: Add macOS Platform Support
        run: flutter create --platforms=macos .

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build macOS Release
        run: flutter build macos --release

      - name: Upload macOS Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: build/macos/Build/Products/Release/

  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
