name: Flutter Windows and Linux Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            platform: windows
            path: build/windows/x64/runner/Release/
          - os: ubuntu-latest
            platform: linux
            path: build/linux/x64/release/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'  # 根据需要指定 Flutter 版本

      - name: Enable Desktop Support
        run: flutter config --enable-windows-desktop --enable-linux-desktop

      - name: Add Platform Support
        run: flutter create --platforms=windows,linux .

      - name: Install dependencies
        run: flutter pub get

      - name: Build Release
        run: |
          if [ "${{ matrix.platform }}" == "windows" ]; then
            flutter build windows --release
          elif [ "${{ matrix.platform }}" == "linux" ]; then
            flutter build linux --release
          fi

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-release
          path: ${{ matrix.path }}
