name: Flutter Windows Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'  # 根据需要指定 Flutter 版本

      - name: Install dependencies
        run: flutter pub get

      # 如果项目中有测试用例，可以启用这一步
      - name: Run tests
        run: flutter test

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: build/windows/runner/Release/
