name: Flutter Windows Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'  # 根据需要指定 Flutter 版本

      - name: Enable Windows Desktop Support
        run: flutter config --enable-windows-desktop

      - name: Add Windows Platform Support
        run: flutter create --platforms=windows .

      - name: Install dependencies
        run: flutter pub get
        
      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release/
